version: "3.9"

services:
  api:
    restart: always
    build:
      context: ./api
    container_name: aweb-api
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
      - "9229:9229"

    env_file:
      - .development.env
    command: npm run start:dev

    depends_on:
      - postgres

  postgres:
    container_name: postgres
    image: postgres:12
    env_file:
      - ./api/.development.env
    environment:
      PG_DATA: /var/lib/postgresql/data
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

volumes:
  pgdata: