version: "3.9"

services:
  app:
    build:
      args:
        NODE_ENV: development
    ports:
      - "3000:3000"
    volumes:
      - /app/node_modules
      - ./app/public:/app/public:ro
      - ./app/src:/app/src:ro
    env_file:
      - .development.env
    environment:
      - NODE_ENV=development

    command: npm run start:dev

  api:
    build:
      args:
        NODE_ENV: development
    volumes:
      - /app/node_modules
      - ./api:/app
    env_file:
      - .development.env

    environment:
      - NODE_ENV=development

    command: npm run start:dev

  postgres:
    env_file:
      - api/.development.env