version: "3.9"

services:
  app:
    container_name: aweb-client
    build:
      context: ./app

    depends_on:
      - api
    restart: always

  api:
    container_name: aweb-api
    build:
      context: ./api
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
      - "9229:9229"
    depends_on:
      - postgres
    restart: always

  postgres:
    container_name: postgres
    image: postgres:12
    environment:
      PG_DATA: /var/lib/postgresql/data
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

volumes:
  pgdata: