version: "3.9"

services:
  api:
    build:
      args:
        NODE_ENV: development
    volumes:
      - /app/node_modules
      - ./api:/app
    env_file:
      - .development.env

    environment:
      - NODE_ENV=development

    command: npm run start:dev